language: c
compiler:
  - gcc
  - clang
sudo: false
before_install:
  - pip install cpp-coveralls --use-mirrors
script:
  - make CFLAGS="-Wall -Wextra -Werror -O2 --coverage"
  - ./polld --version
  - ./polld --help
after_success:
  - coveralls
