.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH POLLD 1 "October  3, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
polld \- program to periodically poll devices
.SH SYNOPSIS
.B polld
[\fIOPTION\fR]
.SH DESCRIPTION
This manual page documents briefly the
.B polld
command.
.PP
\fBpolld\fP is a program that peridically opens files listed in configuration.
.PP
Program accepts following options:
.TP
\fB\-h\fR, \fB\-\-help\fR
shows help
.TP
\fB\-v\fR, \fB\-\-version\fR
shows version information
.TP
\fB\-c\fR, \fB\-\-config\fR=\fIfile\fR
configuration file to use
.TP
\fB\-p\fR, \fB\-\-pid\fR=\fIfile\fR
lock file for storing pid, empty for no locking
.TP
\fB\-s\fR, \fB\-\-sleep\fR=\fIseconds\fR
number of seconds to sleep between polling devices
.SH SEE ALSO
polld(5)
.SH AUTHOR
polld and this manual page were written by Michal Cihar <michal@cihar.com>.
.SH BUGS
Probably.
Report to <URL:http://bugs.cihar.com>.
